### ISSUE TITLE
Video playback returns 403

### ISSUE THREAD

**Issue by jiridostal** [Gujal00/plugin.video.dailymotion_com#5]
Every video I try to play returns 403 since yesterday. I've done some debugging and seems like "dmvk" cookie needs to be set in order to play the video. This is more a question - is this reproducible by anyone else?

**Comment by Gujal00** [comment]
Yes, seems to be Kodi18 quirk.
dmvk cookie is handled correctly and video is opened. Same time Kodi 18 is trying to do a content lookup without the cookie and fails

**Comment by jiridostal** [comment]
Works like a charm. Thanks!
